// lib/ai/actions/handleInterviewAnswer.ts

import { AIResponse, UserContext, InterviewState } from '../types';

/**
 * Generates a portfolio README from the interview answers.
 */
function generatePortfolioReadme(answers: Record<string, string>): string {
  let readme = `# My Developer Story\n\n`;
  
  if (answers.passion) {
    readme += `## 🔥 My Passion\n\n${answers.passion}\n\n`;
  }
  if (answers.journey) {
    readme += `## 🚀 My Journey\n\n${answers.journey}\n\n`;
  }
  if (answers.proudest_project) {
    readme += `## 🏆 My Proudest Project\n\n${answers.proudest_project}\n\n`;
  }
  if (answers.biggest_challenge) {
    readme += `## 💪 My Biggest Challenge\n\n${answers.biggest_challenge}\n\n`;
  }
  if (answers.future_goals) {
    readme += `## ✨ My Future Goals\n\n${answers.future_goals}\n\n`;
  }

  readme += `*This README was auto-generated by NeatRepo AI based on my portfolio interview.*`;

  return readme;
}


/**
 * Handles a user's answer during a portfolio interview.
 */
export async function handleInterviewAnswer(
  context: UserContext,
  params: { answer: string }
): Promise<AIResponse> {
  const { interviewState } = context;
  const { answer } = params;

  if (!interviewState || !interviewState.isActive) {
    return {
      message: "There's no interview currently active. Say 'start interview' to begin.",
      success: false,
    };
  }

  // Create a new state object to avoid direct mutation
  const newInterviewState: InterviewState = JSON.parse(JSON.stringify(interviewState));

  // Store the answer
  const currentQuestionId = newInterviewState.questions[newInterviewState.currentQuestion].id;
  newInterviewState.answers[currentQuestionId] = answer;

  // Move to the next question
  newInterviewState.currentQuestion++;

  // Check if the interview is complete
  if (newInterviewState.currentQuestion >= newInterviewState.questions.length) {
    newInterviewState.isActive = false;
    const portfolioReadme = generatePortfolioReadme(newInterviewState.answers);
    
    return {
      message: `🎉 Interview Complete! I've generated a portfolio README based on your answers:\n\n---\n\n${portfolioReadme}`,
      success: true,
      data: { interviewState: newInterviewState },
    };
  }

  // Ask the next question
  const nextQuestion = newInterviewState.questions[newInterviewState.currentQuestion];
  
  return {
    message: `Great, thanks for sharing! Here's the next question:\n\n${nextQuestion.question}`,
    success: true,
    data: { interviewState: newInterviewState },
  };
}
